baseurl = "https://blog.lanzani.nl"
disablePathToLower = true
languageCode = "en-us"
title = "Technical inconsistencies blog"
theme = 'hugola'

[params]
Domain = "http://www.lanzani.nl"
Name = "lanzani.nl"
Rss = "https://blog.lanzani.nl/atom.xml"
Author = "Giovanni Lanzani"

[params.sidebar]
search = "http://duckduckgo.com/?q=site%3Alanzani.nl"
blog = "/"
cv = "https://lanzani.nl/cv/"
publications = "https://lanzani.nl/publications/"
public = "https://lanzani.nl/public/"

[params.umami]
base_site = "https://umami.lanzani.nl"
base_site_id = "19952d0d-2825-4b1a-bb20-f1bca512b0a6"

[params.footer]
Contact = "mailto:giovanni at this domain?subject=feedback"
X = "http://twitter.com/gglanzani/"
GitHub = "http://github.com/gglanzani/"
Mastodon = "https://mastodon.social/@gla"
LinkedIn = "http://nl.linkedin.com/pub/giovanni-lanzani/24/618/195"


[outputs]
home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      noclasses = false
